"""Creating all the tables

Revision ID: 7f3f931f1e9b
Revises: 
Create Date: 2025-03-30 05:54:27.131240

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7f3f931f1e9b'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id_number', sa.Integer(), autoincrement=True, nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id_number'),
    sa.UniqueConstraint('email')
    )
    op.create_table('socialmediaposts',
    sa.Column('id_number', sa.Integer(), autoincrement=True, nullable=True),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('content', sa.String(), nullable=False),
    sa.Column('published', sa.Boolean(), server_default='True', nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('owner_email', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['owner_email'], ['users.email'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id_number')
    )
    op.create_table('votes',
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['socialmediaposts.id_number'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id_number'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('post_id', 'user_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('votes')
    op.drop_table('socialmediaposts')
    op.drop_table('users')
    # ### end Alembic commands ###
